// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: CommonModels.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LevelProjection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Difficulty int32  `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
}

func (x *LevelProjection) Reset() {
	*x = LevelProjection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_CommonModels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LevelProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelProjection) ProtoMessage() {}

func (x *LevelProjection) ProtoReflect() protoreflect.Message {
	mi := &file_CommonModels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelProjection.ProtoReflect.Descriptor instead.
func (*LevelProjection) Descriptor() ([]byte, []int) {
	return file_CommonModels_proto_rawDescGZIP(), []int{0}
}

func (x *LevelProjection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LevelProjection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LevelProjection) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

var File_CommonModels_proto protoreflect.FileDescriptor

var file_CommonModels_proto_rawDesc = []byte{
	0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x0f,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75, 0x6c, 0x74,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x66, 0x66, 0x69, 0x63, 0x75,
	0x6c, 0x74, 0x79, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x75, 0x64, 0x61, 0x6b, 0x70, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_CommonModels_proto_rawDescOnce sync.Once
	file_CommonModels_proto_rawDescData = file_CommonModels_proto_rawDesc
)

func file_CommonModels_proto_rawDescGZIP() []byte {
	file_CommonModels_proto_rawDescOnce.Do(func() {
		file_CommonModels_proto_rawDescData = protoimpl.X.CompressGZIP(file_CommonModels_proto_rawDescData)
	})
	return file_CommonModels_proto_rawDescData
}

var file_CommonModels_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_CommonModels_proto_goTypes = []interface{}{
	(*LevelProjection)(nil), // 0: common.LevelProjection
}
var file_CommonModels_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_CommonModels_proto_init() }
func file_CommonModels_proto_init() {
	if File_CommonModels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_CommonModels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LevelProjection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_CommonModels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_CommonModels_proto_goTypes,
		DependencyIndexes: file_CommonModels_proto_depIdxs,
		MessageInfos:      file_CommonModels_proto_msgTypes,
	}.Build()
	File_CommonModels_proto = out.File
	file_CommonModels_proto_rawDesc = nil
	file_CommonModels_proto_goTypes = nil
	file_CommonModels_proto_depIdxs = nil
}
