// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: session.proto

package infrastructure

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	JoinSession(ctx context.Context, opts ...grpc.CallOption) (Session_JoinSessionClient, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (Session_ListSessionsClient, error)
}

type sessionClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionClient(cc grpc.ClientConnInterface) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/session.session/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) JoinSession(ctx context.Context, opts ...grpc.CallOption) (Session_JoinSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Session_ServiceDesc.Streams[0], "/session.session/JoinSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionJoinSessionClient{stream}
	return x, nil
}

type Session_JoinSessionClient interface {
	Send(*JoinSessionRequest) error
	CloseAndRecv() (*Session, error)
	grpc.ClientStream
}

type sessionJoinSessionClient struct {
	grpc.ClientStream
}

func (x *sessionJoinSessionClient) Send(m *JoinSessionRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sessionJoinSessionClient) CloseAndRecv() (*Session, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Session)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (Session_ListSessionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Session_ServiceDesc.Streams[1], "/session.session/ListSessions", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionListSessionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Session_ListSessionsClient interface {
	Recv() (*Session, error)
	grpc.ClientStream
}

type sessionListSessionsClient struct {
	grpc.ClientStream
}

func (x *sessionListSessionsClient) Recv() (*Session, error) {
	m := new(Session)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SessionServer is the server API for Session service.
// All implementations must embed UnimplementedSessionServer
// for forward compatibility
type SessionServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	JoinSession(Session_JoinSessionServer) error
	ListSessions(*ListSessionsRequest, Session_ListSessionsServer) error
	mustEmbedUnimplementedSessionServer()
}

// UnimplementedSessionServer must be embedded to have forward compatible implementations.
type UnimplementedSessionServer struct {
}

func (UnimplementedSessionServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionServer) JoinSession(Session_JoinSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedSessionServer) ListSessions(*ListSessionsRequest, Session_ListSessionsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionServer) mustEmbedUnimplementedSessionServer() {}

// UnsafeSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServer will
// result in compilation errors.
type UnsafeSessionServer interface {
	mustEmbedUnimplementedSessionServer()
}

func RegisterSessionServer(s grpc.ServiceRegistrar, srv SessionServer) {
	s.RegisterService(&Session_ServiceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_JoinSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SessionServer).JoinSession(&sessionJoinSessionServer{stream})
}

type Session_JoinSessionServer interface {
	SendAndClose(*Session) error
	Recv() (*JoinSessionRequest, error)
	grpc.ServerStream
}

type sessionJoinSessionServer struct {
	grpc.ServerStream
}

func (x *sessionJoinSessionServer) SendAndClose(m *Session) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sessionJoinSessionServer) Recv() (*JoinSessionRequest, error) {
	m := new(JoinSessionRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Session_ListSessions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSessionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionServer).ListSessions(m, &sessionListSessionsServer{stream})
}

type Session_ListSessionsServer interface {
	Send(*Session) error
	grpc.ServerStream
}

type sessionListSessionsServer struct {
	grpc.ServerStream
}

func (x *sessionListSessionsServer) Send(m *Session) error {
	return x.ServerStream.SendMsg(m)
}

// Session_ServiceDesc is the grpc.ServiceDesc for Session service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Session_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Session_CreateSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinSession",
			Handler:       _Session_JoinSession_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ListSessions",
			Handler:       _Session_ListSessions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "session.proto",
}

// LevelClient is the client API for Level service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LevelClient interface {
	UploadLevel(ctx context.Context, in *CreateLevelRequest, opts ...grpc.CallOption) (*Level, error)
	ListLevels(ctx context.Context, in *ListLevelsRequest, opts ...grpc.CallOption) (Level_ListLevelsClient, error)
}

type levelClient struct {
	cc grpc.ClientConnInterface
}

func NewLevelClient(cc grpc.ClientConnInterface) LevelClient {
	return &levelClient{cc}
}

func (c *levelClient) UploadLevel(ctx context.Context, in *CreateLevelRequest, opts ...grpc.CallOption) (*Level, error) {
	out := new(Level)
	err := c.cc.Invoke(ctx, "/session.level/UploadLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelClient) ListLevels(ctx context.Context, in *ListLevelsRequest, opts ...grpc.CallOption) (Level_ListLevelsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Level_ServiceDesc.Streams[0], "/session.level/ListLevels", opts...)
	if err != nil {
		return nil, err
	}
	x := &levelListLevelsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Level_ListLevelsClient interface {
	Recv() (*Level, error)
	grpc.ClientStream
}

type levelListLevelsClient struct {
	grpc.ClientStream
}

func (x *levelListLevelsClient) Recv() (*Level, error) {
	m := new(Level)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LevelServer is the server API for Level service.
// All implementations must embed UnimplementedLevelServer
// for forward compatibility
type LevelServer interface {
	UploadLevel(context.Context, *CreateLevelRequest) (*Level, error)
	ListLevels(*ListLevelsRequest, Level_ListLevelsServer) error
	mustEmbedUnimplementedLevelServer()
}

// UnimplementedLevelServer must be embedded to have forward compatible implementations.
type UnimplementedLevelServer struct {
}

func (UnimplementedLevelServer) UploadLevel(context.Context, *CreateLevelRequest) (*Level, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLevel not implemented")
}
func (UnimplementedLevelServer) ListLevels(*ListLevelsRequest, Level_ListLevelsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListLevels not implemented")
}
func (UnimplementedLevelServer) mustEmbedUnimplementedLevelServer() {}

// UnsafeLevelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LevelServer will
// result in compilation errors.
type UnsafeLevelServer interface {
	mustEmbedUnimplementedLevelServer()
}

func RegisterLevelServer(s grpc.ServiceRegistrar, srv LevelServer) {
	s.RegisterService(&Level_ServiceDesc, srv)
}

func _Level_UploadLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServer).UploadLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.level/UploadLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServer).UploadLevel(ctx, req.(*CreateLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Level_ListLevels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListLevelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LevelServer).ListLevels(m, &levelListLevelsServer{stream})
}

type Level_ListLevelsServer interface {
	Send(*Level) error
	grpc.ServerStream
}

type levelListLevelsServer struct {
	grpc.ServerStream
}

func (x *levelListLevelsServer) Send(m *Level) error {
	return x.ServerStream.SendMsg(m)
}

// Level_ServiceDesc is the grpc.ServiceDesc for Level service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Level_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.level",
	HandlerType: (*LevelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadLevel",
			Handler:    _Level_UploadLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListLevels",
			Handler:       _Level_ListLevels_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "session.proto",
}
