// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: session.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SessionClient is the client API for Session service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	// result session stream contains updated session state
	JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (Session_JoinSessionClient, error)
	// result contains finite list of sessions
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (Session_ListSessionsClient, error)
}

type sessionClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionClient(cc grpc.ClientConnInterface) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := c.cc.Invoke(ctx, "/session.session/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionClient) JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (Session_JoinSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Session_ServiceDesc.Streams[0], "/session.session/JoinSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionJoinSessionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Session_JoinSessionClient interface {
	Recv() (*Session, error)
	grpc.ClientStream
}

type sessionJoinSessionClient struct {
	grpc.ClientStream
}

func (x *sessionJoinSessionClient) Recv() (*Session, error) {
	m := new(Session)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sessionClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (Session_ListSessionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Session_ServiceDesc.Streams[1], "/session.session/ListSessions", opts...)
	if err != nil {
		return nil, err
	}
	x := &sessionListSessionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Session_ListSessionsClient interface {
	Recv() (*Session, error)
	grpc.ClientStream
}

type sessionListSessionsClient struct {
	grpc.ClientStream
}

func (x *sessionListSessionsClient) Recv() (*Session, error) {
	m := new(Session)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SessionServer is the server API for Session service.
// All implementations must embed UnimplementedSessionServer
// for forward compatibility
type SessionServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	// result session stream contains updated session state
	JoinSession(*JoinSessionRequest, Session_JoinSessionServer) error
	// result contains finite list of sessions
	ListSessions(*ListSessionsRequest, Session_ListSessionsServer) error
	mustEmbedUnimplementedSessionServer()
}

// UnimplementedSessionServer must be embedded to have forward compatible implementations.
type UnimplementedSessionServer struct {
}

func (UnimplementedSessionServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionServer) JoinSession(*JoinSessionRequest, Session_JoinSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedSessionServer) ListSessions(*ListSessionsRequest, Session_ListSessionsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSessionServer) mustEmbedUnimplementedSessionServer() {}

// UnsafeSessionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionServer will
// result in compilation errors.
type UnsafeSessionServer interface {
	mustEmbedUnimplementedSessionServer()
}

func RegisterSessionServer(s grpc.ServiceRegistrar, srv SessionServer) {
	s.RegisterService(&Session_ServiceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Session_JoinSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinSessionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionServer).JoinSession(m, &sessionJoinSessionServer{stream})
}

type Session_JoinSessionServer interface {
	Send(*Session) error
	grpc.ServerStream
}

type sessionJoinSessionServer struct {
	grpc.ServerStream
}

func (x *sessionJoinSessionServer) Send(m *Session) error {
	return x.ServerStream.SendMsg(m)
}

func _Session_ListSessions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSessionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionServer).ListSessions(m, &sessionListSessionsServer{stream})
}

type Session_ListSessionsServer interface {
	Send(*Session) error
	grpc.ServerStream
}

type sessionListSessionsServer struct {
	grpc.ServerStream
}

func (x *sessionListSessionsServer) Send(m *Session) error {
	return x.ServerStream.SendMsg(m)
}

// Session_ServiceDesc is the grpc.ServiceDesc for Session service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Session_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Session_CreateSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinSession",
			Handler:       _Session_JoinSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSessions",
			Handler:       _Session_ListSessions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "session.proto",
}
