// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: Level.proto

package internal

import (
	proto "github.com/dudakp/input-server/internal/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateLevelRequest) Reset() {
	*x = CreateLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Level_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLevelRequest) ProtoMessage() {}

func (x *CreateLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLevelRequest.ProtoReflect.Descriptor instead.
func (*CreateLevelRequest) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLevelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLevelRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListLevelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListLevelsRequest) Reset() {
	*x = ListLevelsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Level_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLevelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLevelsRequest) ProtoMessage() {}

func (x *ListLevelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Level_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLevelsRequest.ProtoReflect.Descriptor instead.
func (*ListLevelsRequest) Descriptor() ([]byte, []int) {
	return file_Level_proto_rawDescGZIP(), []int{1}
}

var File_Level_proto protoreflect.FileDescriptor

var file_Level_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x91, 0x01, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x43, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x4c,
	0x69, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x12, 0x18, 0x2e, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x75, 0x64, 0x61, 0x6b, 0x70, 0x2f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x70,
	0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Level_proto_rawDescOnce sync.Once
	file_Level_proto_rawDescData = file_Level_proto_rawDesc
)

func file_Level_proto_rawDescGZIP() []byte {
	file_Level_proto_rawDescOnce.Do(func() {
		file_Level_proto_rawDescData = protoimpl.X.CompressGZIP(file_Level_proto_rawDescData)
	})
	return file_Level_proto_rawDescData
}

var file_Level_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Level_proto_goTypes = []interface{}{
	(*CreateLevelRequest)(nil),    // 0: level.CreateLevelRequest
	(*ListLevelsRequest)(nil),     // 1: level.ListLevelsRequest
	(*proto.LevelProjection)(nil), // 2: common.LevelProjection
}
var file_Level_proto_depIdxs = []int32{
	0, // 0: level.level.UploadLevel:input_type -> level.CreateLevelRequest
	1, // 1: level.level.ListLevels:input_type -> level.ListLevelsRequest
	2, // 2: level.level.UploadLevel:output_type -> common.LevelProjection
	2, // 3: level.level.ListLevels:output_type -> common.LevelProjection
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Level_proto_init() }
func file_Level_proto_init() {
	if File_Level_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Level_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Level_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLevelsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Level_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Level_proto_goTypes,
		DependencyIndexes: file_Level_proto_depIdxs,
		MessageInfos:      file_Level_proto_msgTypes,
	}.Build()
	File_Level_proto = out.File
	file_Level_proto_rawDesc = nil
	file_Level_proto_goTypes = nil
	file_Level_proto_depIdxs = nil
}
