// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: Level.proto

package internal

import (
	context "context"
	proto "github.com/dudakp/input-server/internal/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LevelClient is the client API for Level service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LevelClient interface {
	UploadLevel(ctx context.Context, in *CreateLevelRequest, opts ...grpc.CallOption) (*proto.LevelProjection, error)
	ListLevels(ctx context.Context, in *ListLevelsRequest, opts ...grpc.CallOption) (Level_ListLevelsClient, error)
}

type levelClient struct {
	cc grpc.ClientConnInterface
}

func NewLevelClient(cc grpc.ClientConnInterface) LevelClient {
	return &levelClient{cc}
}

func (c *levelClient) UploadLevel(ctx context.Context, in *CreateLevelRequest, opts ...grpc.CallOption) (*proto.LevelProjection, error) {
	out := new(proto.LevelProjection)
	err := c.cc.Invoke(ctx, "/level.level/UploadLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *levelClient) ListLevels(ctx context.Context, in *ListLevelsRequest, opts ...grpc.CallOption) (Level_ListLevelsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Level_ServiceDesc.Streams[0], "/level.level/ListLevels", opts...)
	if err != nil {
		return nil, err
	}
	x := &levelListLevelsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Level_ListLevelsClient interface {
	Recv() (*proto.LevelProjection, error)
	grpc.ClientStream
}

type levelListLevelsClient struct {
	grpc.ClientStream
}

func (x *levelListLevelsClient) Recv() (*proto.LevelProjection, error) {
	m := new(proto.LevelProjection)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LevelServer is the server API for Level service.
// All implementations must embed UnimplementedLevelServer
// for forward compatibility
type LevelServer interface {
	UploadLevel(context.Context, *CreateLevelRequest) (*proto.LevelProjection, error)
	ListLevels(*ListLevelsRequest, Level_ListLevelsServer) error
	mustEmbedUnimplementedLevelServer()
}

// UnimplementedLevelServer must be embedded to have forward compatible implementations.
type UnimplementedLevelServer struct {
}

func (UnimplementedLevelServer) UploadLevel(context.Context, *CreateLevelRequest) (*proto.LevelProjection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLevel not implemented")
}
func (UnimplementedLevelServer) ListLevels(*ListLevelsRequest, Level_ListLevelsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListLevels not implemented")
}
func (UnimplementedLevelServer) mustEmbedUnimplementedLevelServer() {}

// UnsafeLevelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LevelServer will
// result in compilation errors.
type UnsafeLevelServer interface {
	mustEmbedUnimplementedLevelServer()
}

func RegisterLevelServer(s grpc.ServiceRegistrar, srv LevelServer) {
	s.RegisterService(&Level_ServiceDesc, srv)
}

func _Level_UploadLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LevelServer).UploadLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/level.level/UploadLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LevelServer).UploadLevel(ctx, req.(*CreateLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Level_ListLevels_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListLevelsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LevelServer).ListLevels(m, &levelListLevelsServer{stream})
}

type Level_ListLevelsServer interface {
	Send(*proto.LevelProjection) error
	grpc.ServerStream
}

type levelListLevelsServer struct {
	grpc.ServerStream
}

func (x *levelListLevelsServer) Send(m *proto.LevelProjection) error {
	return x.ServerStream.SendMsg(m)
}

// Level_ServiceDesc is the grpc.ServiceDesc for Level service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Level_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "level.level",
	HandlerType: (*LevelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadLevel",
			Handler:    _Level_UploadLevel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListLevels",
			Handler:       _Level_ListLevels_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "Level.proto",
}
